name: Deploy Log Analyzer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user
            rm -rf log-analyzer-devops
            git clone https://github.com/vani-siva1020/log-analyzer-devops.git
            cd log-analyzer-devops
            sudo docker build -t log-app .
            sudo docker stop log-app || true
            sudo docker rm log-app || true
            sudo docker run -d -p 5002:5002 --name log-app log-app
